apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes: 
  - role: control-plane
  kubeadmconfigpatches:
    -
      kind: InitConfiguration
      modeRegistration:
        kubeleExtraArgs:
          node-labels: "ingress-ready=true"

  extraPortMappings:
    - containerport: 31515
      hostPort: 31515
      protocol: tcp
    - containerPort: 3000
      hostPort: 3000
      protocol: tcp
    - containerPort: 80
      hostPort: 3000
      protocol: tcp
- role: worker 