apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: api
          image: docker.io/priyac579/simple_blog_api
          ports:
            - containerPort: 3000
          resources:
              limits:
                memory: "128Mi"
                cpu: "500m"